djangocrud/urls.py
#urls.py from djangocrud ( principal app )
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
]

task/urls.py
#urls.py from task
from django.contrib import admin
from django.urls import path
from . import views
from .views import MarcaListCreate, ColorListCreate, descargar_comprobante_pdf


urlpatterns = [
    #path('admin', admin.site.urls),
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('logout/', views.logout_view, name='logout'),
    path('listar/', views.listar, name='listar'),
    path('pagos/', views.pagos, name='pagos'),
    path('crear_cliente/', views.crear_cliente, name='crear_cliente'),
    path('clientes/', views.listar_clientes, name='listar_clientes'),
    path('buscar_cliente/', views.buscar_cliente, name='buscar_cliente'),
    path('venta_contado/', views.venta_contado, name='venta_contado'),
    path('venta_credito/', views.venta_credito, name='venta_credito'),
    path('abonar/<int:venta_id>/', views.abonar, name='abonar'),
    path('pendiente_pago/', views.pendiente_pago, name='pendiente_pago'),
    path('alertas/', views.alertas, name='alertas'),
    path('productos/', views.productos, name='productos'),
    path('categorias/', views.categorias, name='categorias'),
    path('AgregarProducto/', views.agregarProducto, name='AgregarProducto'),
    path('obtener_producto/', views.obtener_producto, name='obtener_producto'),
    path('buscar_producto/', views.buscar_producto, name='buscar_producto'),
    path('marcas/', MarcaListCreate.as_view(), name='marcas'),
    path('marcas/agregar/', views.agregar_marca, name='agregar_marca'),
    path('colores/', ColorListCreate.as_view(), name='colores'),
    path('colores/agregar/', views.agregar_color, name='agregar_color'),  
    path('descargar_comprobante/<int:venta_id>/', descargar_comprobante_pdf, name='descargar_comprobante'),
    path('descargar_comprobante_pago/<int:pago_id>/', views.descargar_comprobante_pago, name='descargar_comprobante_pago'),
    path('obtener_notificaciones/', views.obtener_notificaciones, name='obtener_notificaciones'), 
]

task/models.py
# models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Tienda(models.Model):
    nombre = models.CharField(max_length=255)
    ubicacion = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField(max_length=255, blank=True)
    precio_compra = models.DecimalField(max_digits=10, decimal_places=2)
    precio_venta = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()

    # Relaciones con otras tablas
    color = models.ForeignKey('Color', on_delete=models.CASCADE)
    marca = models.ForeignKey('Marca', on_delete=models.CASCADE)
    tamano = models.ForeignKey('Tamano', on_delete=models.CASCADE)
    proveedor = models.ForeignKey('Proveedor', on_delete=models.CASCADE)  # Relación con Proveedor
    tienda = models.ForeignKey('Tienda', on_delete=models.CASCADE)        # Relación con Tienda

    def __str__(self):
        return f"{self.nombre} ({self.color.nombre})"


   
class Proveedor(models.Model):
    nombre = models.CharField(max_length=255)
    correo = models.EmailField()
    telefono = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre

# Atributos de los productos.

class Color(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre
    
class Marca(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre
    
class Tamano(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre
    
class Vendedor(models.Model):
    nombre = models.CharField(max_length=255)
    telefono = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre
    
class Cliente(models.Model):
    nombre = models.CharField(max_length=255)
    correo = models.EmailField()
    telefono = models.CharField(max_length=20)
    direccion = models.CharField(max_length=255)
    nit = models.CharField(max_length=20, blank=True, null=True)  # Campo NIT agregado

    def __str__(self):
        return f"{self.nombre} - NIT: {self.nit}" if self.nit else self.nombre
    
    
# Campos de la venta   
class DetalleVenta(models.Model):
    venta = models.ForeignKey('Venta', on_delete=models.CASCADE) 
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE) 
    cantidad = models.PositiveIntegerField()

    def __str__(self):
     return f"Detalle Venta {self.venta.id} - Producto: {self.producto.nombre}"
    
class Venta(models.Model):
    
    
    descripcion = models.TextField(blank=True)
    fecha_venta = models.DateField()
    tipo_venta = models.CharField(max_length=50)  # Por ejemplo, "Crédito" o "Contado"
    total = models.DecimalField(max_digits=10, decimal_places=2)

    # Relaciones con otras tablas
    tienda = models.ForeignKey('Tienda', on_delete=models.SET_NULL, null=True)
    vendedor = models.ForeignKey('Vendedor', on_delete=models.CASCADE)  # Relación con Vendedor
    comprobante = models.ForeignKey('Comprobante', on_delete=models.CASCADE)  # Relación con Comprobante
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE)  # Relación con Cliente

    def __str__(self):
        return f"Venta {self.id} - Total: {self.total}"
 
class Comprobante(models.Model):
    id_comprobante = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=255)
    tipo_comprobante = models.CharField(max_length=50)
    numero_comprobante = models.CharField(max_length=50, unique=True)
    fecha_emision = models.DateField()
    
    def __str__(self):
        return f"Comprobante {self.numero_comprobante}"

    
class PagoCredito(models.Model):
    venta_credito = models.ForeignKey('VentaCredito', on_delete=models.CASCADE)
    fecha_pago = models.DateField()
    monto_pago = models.DecimalField(max_digits=10, decimal_places=2)
    saldo_pendiente = models.DecimalField(max_digits=10, decimal_places=2)
    
    
class VentaCredito(models.Model):
    FRECUENCIA_PAGO_CHOICES = [
        ('semanal', 'Semanal'),
        ('quincenal', 'Quincenal'),
        ('mensual', 'Mensual'),
    ]
    
    venta = models.OneToOneField('Venta', on_delete=models.CASCADE)  # Relación con Venta
    monto_inicial = models.DecimalField(max_digits=10, decimal_places=2)
    numero_cuotas = models.IntegerField()
    interes = models.DecimalField(max_digits=4, decimal_places=2)  # Limita el interés al 99.99%
    fecha_limite = models.DateField()
    saldo_restante = models.DecimalField(max_digits=10, decimal_places=2)
    
    # Nuevo campo para frecuencia de pago
    frecuencia_pago = models.CharField(max_length=10, choices=FRECUENCIA_PAGO_CHOICES)
    
    def __str__(self):
        return f"Venta Crédito - Cuotas: {self.numero_cuotas}, Frecuencia: {self.get_frecuencia_pago_display()}"

    

    

task/views.py
#views.py
from django.http import HttpResponse, JsonResponse
from django.core.paginator import Paginator
from django.template.loader import render_to_string
from xhtml2pdf import pisa
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib import messages
from django.db import IntegrityError, transaction
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.db.models import Max, Sum, Count
from decimal import Decimal
from datetime import timedelta
from django.db import models 
import datetime

# Third-party imports
from rest_framework import generics

# Local app imports
from .forms import CrearVentaForm, DetalleVentaFormSet, AgregarProductoForm, MarcaForm, ColorForm, CrearVentaCreditoForm, DetalleVentaFormSetCredito
from .models import Comprobante, Venta, Producto, Marca, Color, VentaCredito, PagoCredito, Cliente
from .serializers import MarcaSerializer, ColorSerializer




TEMPLATE_DIRS = (
    
    'os.path.join(BASE_DIR, "templates")'
)


@login_required
def home(request):
    hoy = timezone.now()
    inicio_semana = hoy - timedelta(days=hoy.weekday())  # Lunes de esta semana
    ventas = Venta.objects.filter(fecha_venta__gte=inicio_semana)
    
    ventas_dias = [ventas.filter(fecha_venta=hoy - timedelta(days=d)).count() for d in range(7)]
    ingresos_dias = [ventas.filter(fecha_venta=hoy - timedelta(days=d)).aggregate(total=models.Sum('total'))['total'] or 0 for d in range(7)]
    
    context = {
        'ventas_dias': ventas_dias[::-1],
        'ingresos_dias': ingresos_dias[::-1],
    }
    return render(request, "index.html", context)

#funciones signin, signup, logout

def signin(request):
    if request.method == 'GET':
        return render(request, 'signin.html', {"form": AuthenticationForm})
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'signin.html', {"form": AuthenticationForm, "error": "Username or password is incorrect."})

        login(request, user)
        return redirect('home') 
    

@login_required
def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html', {"form": UserCreationForm})
    else:

        if request.POST["password1"] == request.POST["password2"]:
            try:
                user = User.objects.create_user(
                    request.POST["username"], password=request.POST["password1"])
                user.save()
                login(request, user)
                return redirect('home')
            except IntegrityError:
                return render(request, 'signup.html', {"form": UserCreationForm, "error": "Username already exists."})

        return render(request, 'signup.html', {"form": UserCreationForm, "error": "Passwords did not match."})
   
@login_required
def logout_view(request):
    logout(request)
    return redirect('signin')  # Redirige a la página de inicio de sesión

#funciones crud ventas

@login_required
def listar(request):
    ventas_list = Venta.objects.all().order_by('-fecha_venta')
    
    paginator = Paginator(ventas_list, 10)
    page_number = request.GET.get('page')
    ventas_page = paginator.get_page(page_number)
    
    # Cálculo del índice inicial de la página actual
    page_start_index = (ventas_page.number - 1) * ventas_page.paginator.per_page

    return render(request, 'crud_ventas/listar.html', {
        'venta': ventas_page,
        'page_start_index': page_start_index
    })

@login_required
def listar_clientes(request):
    clientes_list = Cliente.objects.all().order_by('nombre')  # Ordena alfabéticamente por nombre
    paginator = Paginator(clientes_list, 10)  # Cambia el número 10 a la cantidad deseada por página
    page_number = request.GET.get('page')
    clientes = paginator.get_page(page_number)

    context = {
        'clientes': clientes,
    }
    return render(request, 'crud_ventas/listar_clientes.html', context)

@login_required
def productos(request):
    
    producto = Producto.objects.all()
    
    return render (request, 'crud_ventas/productos.html', {
        'producto' : producto
    })


@login_required   
def ventas(request):
    return render (request, 'crud_ventas/ventas.html')   

@login_required
def pagos(request):
    pagos_list = PagoCredito.objects.select_related('venta_credito__venta__cliente').prefetch_related('venta_credito__venta__detalleventa_set__producto').order_by('-fecha_pago')
    paginator = Paginator(pagos_list, 10)  # Cambia 10 por el número de registros que deseas por página
    page_number = request.GET.get('page')
    pagos = paginator.get_page(page_number)

    context = {
        'pagos': pagos,
    }
    return render(request, 'crud_ventas/pagos.html', context)

@login_required 
def alertas(request):
    return render (request, 'crud_ventas/alertas.html')  


@login_required
def agregarProducto(request):
    if request.method == 'POST':
        form = AgregarProductoForm(request.POST)
        if form.is_valid():
            form.save()  # Guarda el nuevo producto en la base de datos
            return redirect('productos')  # Redirige a la página de lista de productos después de guardar
        else:
            print(form.errors)  # Imprimir errores en la consola
    else:
        form = AgregarProductoForm()
    
    return render(request, 'crud_ventas/AgregarProducto.html', {
        'form': form
    })

@login_required
def marcas(request):
    return render (request, 'elementos/marcas.html') 

@login_required
def categorias(request):
    return render (request, 'elementos/categorias.html') 

@login_required
def venta_contado(request):
    if request.method == 'POST':
        print("Formulario enviado correctamente")
        form = CrearVentaForm(request.POST)
        formset = DetalleVentaFormSet(request.POST)

        # Imprimir datos de POST para depuración
        print("Datos POST recibidos:", request.POST)

        if form.is_valid() and formset.is_valid():
            try:
                with transaction.atomic():
                    print("Formulario y formset válidos")

                    comprobante_number = generate_comprobante_number()
                    comprobante = Comprobante(
                        nombre='Comprobante de Venta',
                        tipo_comprobante='Venta Contado',
                        numero_comprobante=comprobante_number,
                        fecha_emision=timezone.now()
                    )
                    comprobante.save()

                    venta = form.save(commit=False)
                    venta.comprobante = comprobante
                    venta.tipo_venta = 'Contado'
                    venta.save()

                    detalles = formset.save(commit=False)
                    for detalle in detalles:
                        detalle.venta = venta
                        producto = detalle.producto
                        if producto.stock >= detalle.cantidad:
                            producto.stock -= detalle.cantidad
                            producto.save()
                        else:
                            raise ValueError(f"Stock insuficiente para el producto: {producto.nombre}")

                        detalle.save()

                print("Venta guardada exitosamente")
                return redirect('listar')

            except Exception as e:
                form.add_error(None, str(e))
                print(f"Error al procesar la venta: {e}")
        else:
            # Depuración de errores de validación del formulario
            print("Formulario o formset no válidos")  
            print("Errores en form:", form.errors)
            for form_error in formset:
                print("Errores en formset:", form_error.errors)
    else:
        form = CrearVentaForm(initial={'tipo_venta': 'Contado'})
        formset = DetalleVentaFormSet()

    return render(request, 'crud_ventas/venta_contado.html', {
        'form': form,
        'formset': formset
    })
    
@login_required
def venta_credito(request):
    if request.method == 'POST':
        form_venta = CrearVentaForm(request.POST)
        form_credito = CrearVentaCreditoForm(request.POST)
        formset = DetalleVentaFormSetCredito(request.POST)

        # Obtener el nuevo total calculado desde el formulario
        nuevo_total = request.POST.get('nuevo_total_input')

        if form_venta.is_valid() and form_credito.is_valid() and formset.is_valid():
            try:
                with transaction.atomic():
                    # Generar número de comprobante
                    comprobante_number = generate_comprobante_number()

                    # Crear y guardar el comprobante
                    comprobante = Comprobante(
                        nombre='Comprobante de Venta a Crédito',
                        tipo_comprobante='Venta Crédito',
                        numero_comprobante=comprobante_number,
                        fecha_emision=timezone.now()
                    )
                    comprobante.save()

                    # Guardar la venta con el tipo de venta 'Crédito'
                    venta = form_venta.save(commit=False)
                    venta.comprobante = comprobante
                    venta.tipo_venta = 'Crédito'
                    venta.total = nuevo_total  # Asignar el nuevo total calculado
                    venta.save()

                    # Guardar los detalles de la venta
                    detalles = formset.save(commit=False)
                    for detalle in detalles:
                        detalle.venta = venta

task/templates/crud_ventas/AgregarProducto.html
{% extends 'index_master.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="right_col" role="main">
    <h1>Agregar Producto</h1>
    
    <form action="" method="POST">
        {% csrf_token %}
        
        <!-- Campo de nombre del producto fuera de los recuadros -->


        <div class="row">
            <!-- Primer recuadro -->
            <div class="col-md-6">
                <div class="card mb-3 shadow-sm">
                    <div class="card-header">
                        <h2>Información del Producto</h2>
                    </div>
                    <div class="card-body">
                        <div class="form-group mb-4">
                            {{ form.nombre.label_tag }}
                            {{ form.nombre|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            {{ form.descripcion.label_tag }}
                            {{ form.descripcion|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            {{ form.precio_compra.label_tag }}
                            {{ form.precio_compra|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            {{ form.precio_venta.label_tag }}
                            {{ form.precio_venta|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            {{ form.stock.label_tag }}
                            {{ form.stock|add_class:"form-control" }}
                        </div>
                    </div>
                </div>
            </div>

            <!-- Segundo recuadro -->
            <div class="col-md-6">
                <div class="card mb-3 shadow-sm">
                    <div class="card-header">
                        <h2>Atributos del Producto</h2>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            {{ form.color.label_tag }}
                            {{ form.color|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            {{ form.marca.label_tag }}
                            {{ form.marca|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            {{ form.tamano.label_tag }}
                            {{ form.tamano|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            {{ form.proveedor.label_tag }}
                            {{ form.proveedor|add_class:"form-control" }}
                        </div>
                        <div class="form-group">
                            {{ form.tienda.label_tag }}
                            {{ form.tienda|add_class:"form-control" }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-success">
            Agregar Producto <i class="fa-solid fa-circle-plus"></i>
        </button>
    </form>
</div>
{% endblock %}

task/templates/crud_ventas/alertas.html
<!-- alertas.html -->
{% extends 'index_master.html' %}

{% block content %}

<div class="right_col" role="main">   
    <div class="container mt-4">
        <h2>Todas las Notificaciones</h2>
        <ul class="list-group">
            {% for notificacion in notificaciones %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <span class="badge {% if notificacion.tipo == 'urgente' %}bg-danger{% else %}bg-warning{% endif %}">
                        {{ notificacion.tipo|title }}
                    </span>
                    <span class="message">{{ notificacion.mensaje }}</span>
                </li>
            {% empty %}
                <li class="list-group-item text-center">No hay notificaciones</li>
            {% endfor %}
        </ul>
    </div>
</div>    
{% endblock %}

task/templates/crud_ventas/pagos.html
{% extends 'index_master.html' %}

{% block content %}
<div class="right_col" role="main">
    <h1>Historial de Pagos</h1>
    <div class="table-responsive">
        <table class="table table-striped table-borderless table-sm table-light">
            <!-- Encabezado de la tabla -->
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Cliente</th>
                    <th scope="col">Producto</th>
                    <th scope="col">Fecha de Pago</th>
                    <th scope="col">Monto Pagado</th>
                    <th scope="col">Saldo Pendiente</th>
                    <th scope="col">Número de Venta</th>
                    <th scope="col">Comprobante</th>
                </tr>
            </thead>
            <!-- Cuerpo de la tabla -->
            <tbody>
                {% for pago in pagos %}
                <tr>
                    <th scope="row">{{ pago.id }}</th>
                    <td>{{ pago.venta_credito.venta.cliente.nombre }}</td>
                    <td>
                        {% for detalle in pago.venta_credito.venta.detalleventa_set.all %}
                            {{ detalle.producto.nombre }}
                            {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </td>
                    <td>{{ pago.fecha_pago }}</td>
                    <td>{{ pago.monto_pago }}</td>
                    <td>{{ pago.saldo_pendiente }}</td>
                    <td>{{ pago.venta_credito.venta.id }}</td>
                    <td>
                        <a href="{% url 'descargar_comprobante_pago' pago.id %}" class="btn btn-success btn-sm">
                            <i class="fa-solid fa-file-arrow-down me-2"></i> Comprobante
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    
    <!-- Controles de paginación -->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if pagos.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ pagos.previous_page_number }}">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
            {% endif %}
    
            {% for num in pagos.paginator.page_range %}
                {% if pagos.number == num %}
                    <li class="page-item active">
                        <a class="page-link" href="#">{{ num }}</a>
                    </li>
                {% elif num > pagos.number|add:'-3' and num < pagos.number|add:'3' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
    
            {% if pagos.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ pagos.next_page_number }}">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Next</a>
                </li>
            {% endif %}
        </ul>
    </nav>
    
</div>
{% endblock %}

task/templates/crud_ventas/pendiente_pago.html
{% extends 'index_master.html' %}

{% block content %}

<div class="right_col" role="main">
    <h1>Ventas Pendientes de Pago</h1>
    <div class="table-responsive">
      <table class="table table-striped table-borderless table-sm table-light">
          <thead>
              <tr>
                  <th>Número de Venta</th>
                  <th>Cliente</th>
                  <th>Producto</th>
                  <th>Monto Inicial</th>
                  <th>Saldo Restante</th>
                  <th>Fecha de Venta</th>
                  <th>Acciones</th>
              </tr>
          </thead>
          <tbody>
              {% for venta in ventas_pendientes %}
              <tr>
                  <td>{{ venta.venta.id }}</td>
                  <td>{{ venta.venta.cliente.nombre }}</td>
                  <td>
                      {% for detalle in venta.venta.detalleventa_set.all %}
                          {{ detalle.producto.nombre }}{% if not forloop.last %}, {% endif %}
                      {% empty %}
                          Sin productos
                      {% endfor %}
                  </td>
                  <td>{{ venta.monto_inicial }}</td>
                  <td>{{ venta.saldo_restante }}</td>
                  <td>{{ venta.venta.fecha_venta }}</td>
                  <td>
                      <button class="btn btn-success btn-sm" data-toggle="modal" data-target="#abonoModal-{{ venta.id }}">
                          <i class="fa-solid fa-hand-holding-medical"></i> Abonar
                      </button>
                  </td>
              </tr>
              <!-- Modal de abono -->
              <div class="modal fade" id="abonoModal-{{ venta.id }}" tabindex="-1" aria-labelledby="abonoModalLabel"
                  aria-hidden="true">
                  <div class="modal-dialog">
                      <div class="modal-content">
                          <div class="modal-header">
                              <h5 class="modal-title" id="abonoModalLabel">Abonar a Venta {{ venta.venta.id }}</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                              </button>
                          </div>
                          <div class="modal-body">
                            <form action="{% url 'abonar' venta.id %}" method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="monto_abono">Monto a abonar:</label>
                                    <!-- Aquí se añade el atributo 'value' con el monto inicial -->
                                    <input type="number" step="0.01" class="form-control" name="monto_abono" required value="{{ venta.monto_inicial }}">
                                </div>
                                <button type="submit" class="btn btn-success btn-sm">
                                    <i class="fa-solid fa-hand-holding-medical"></i> Realizar Abono
                                </button>
                            </form>
                        </div>
                      </div>
                  </div>
              </div>
              {% empty %}
              <tr>
                  <td colspan="7">No hay ventas pendientes de pago.</td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
  </div>

    <!-- Controles de paginación -->
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        {% if ventas_pendientes.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ ventas_pendientes.previous_page_number }}">Previous</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Previous</a>
          </li>
        {% endif %}

        {% for num in ventas_pendientes.paginator.page_range %}
          {% if ventas_pendientes.number == num %}
            <li class="page-item active">
              <a class="page-link" href="#">{{ num }}</a>
            </li>
          {% elif num > ventas_pendientes.number|add:'-3' and num < ventas_pendientes.number|add:'3' %}
            <li class="page-item">
              <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
          {% endif %}
        {% endfor %}

        {% if ventas_pendientes.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ ventas_pendientes.next_page_number }}">Next</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Next</a>
          </li>
        {% endif %}
      </ul>
    </nav>
</div>

{% endblock %}

task/templates/crud_ventas/productos.html
{% extends 'index_master.html' %}

{% block content %}

<div class="right_col" role="main">

    <h1>Listado de Productos</h1>

    <div class="table-responsive">
        <table class="table table-striped table-borderless table-sm table-light">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Nombre del Producto</th>
              <th scope="col">Precio</th>
              <th scope="col">Color</th>
              <th scope="col">Stock Disponible</th>
            </tr>
          </thead>
          <tbody>
            {% for producto in producto %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th> <!-- Número de fila -->
              <td>{{ producto.nombre }}</td>
              <td>{{ producto.precio_venta }}</td>
              <td>{{ producto.color.nombre }}</td>
              <td>{{ producto.stock }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>

</div>

{% endblock %}